<?php

namespace tests\PluginHttpClientPassportLaravel;

use PHPUnit\Framework\TestCase;

class BaseTest extends TestCase
{
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown()
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }
}
